Repository wecode-bootcamp-korea/11-WeCha-frontend, pull requests merged in 2020-08, with the labels that each got.

#4 Fix: font-weight가 적용되지 않는 문제 해결
  package-lock.json
  package.json
  public/index.html
Labels: Status: 리뷰 요청

#6 Modify: box-sizing: border-box 기본 적용
  src/Styles/reset.scss
Labels: Status: Accepted

#10 [김동호] Modify: media query를 위한 믹스인 추가
  src/Styles/common.scss
Labels: Status: 리뷰 요청

#7 [김동호] Add: Detail 페이지 컴포넌트 구성
  package-lock.json
  package.json
  public/images/empty_movie.svg
  public/images/empty_user.svg
  src/Pages/Detail/Components/Collection/Collection.js
  src/Pages/Detail/Components/Collection/Collection.scss
  src/Pages/Detail/Components/CommentContainer/CommentContainer.js
  src/Pages/Detail/Components/CommentContainer/CommentContainer.scss
  src/Pages/Detail/Components/ContentsContainer/ContentsContainer.js
  src/Pages/Detail/Components/ContentsContainer/ContentsContainer.scss
  src/Pages/Detail/Components/DetailContainer/DetailContainer.js
  src/Pages/Detail/Components/DetailContainer/DetailContainer.scss
  src/Pages/Detail/Components/DetailContainer/RatingGraph/RatingGraph.js
  src/Pages/Detail/Components/DetailContainer/RatingGraph/RatingGraph.scss
  src/Pages/Detail/Components/DetailContainer/SelfCommentBlock/SelfCommentBlock.js
  src/Pages/Detail/Components/DetailContainer/SelfCommentBlock/SelfCommentBlock.scss
  src/Pages/Detail/Components/DetailContainer/ShowCommentBlock/ShowCommentBlock.js
  src/Pages/Detail/Components/DetailContainer/ShowCommentBlock/ShowCommentBlock.scss
  src/Pages/Detail/Components/DetailContainer/ThumbnailImage/ThumbnailImage.js
  src/Pages/Detail/Components/DetailContainer/ThumbnailImage/ThumbnailImage.scss
  src/Pages/Detail/Components/DetailHeader/DetailHeader.js
  src/Pages/Detail/Components/DetailHeader/DetailHeader.scss
  src/Pages/Detail/Components/DetailHeader/HeaderPanelContainer/ArrowDownButton/ArrowDownButton.js
  src/Pages/Detail/Components/DetailHeader/HeaderPanelContainer/ArrowDownButton/ArrowDownButton.scss
  src/Pages/Detail/Components/DetailHeader/HeaderPanelContainer/ButtonBlocks/NomalButtonBlock/NomalButtonBlock.js
  src/Pages/Detail/Components/DetailHeader/HeaderPanelContainer/ButtonBlocks/NomalButtonBlock/NomalButtonBlock.scss
  src/Pages/Detail/Components/DetailHeader/HeaderPanelContainer/ButtonBlocks/StatusButtonBlock/StatusButtonBlock.js
  src/Pages/Detail/Components/DetailHeader/HeaderPanelContainer/ButtonBlocks/StatusButtonBlock/StatusButtonBlock.scss
  src/Pages/Detail/Components/DetailHeader/HeaderPanelContainer/HeaderPanelContainer.js
  src/Pages/Detail/Components/DetailHeader/HeaderPanelContainer/HeaderPanelContainer.scss
  src/Pages/Detail/Components/DetailHeader/HeaderPanelContainer/SelfRating/SelfRating.js
  src/Pages/Detail/Components/DetailHeader/HeaderPanelContainer/SelfRating/SelfRating.scss
  src/Pages/Detail/Components/DetailHeader/HeaderPosterContainer/HeaderPosterContainer.js
  src/Pages/Detail/Components/DetailHeader/HeaderPosterContainer/HeaderPosterContainer.scss
  src/Pages/Detail/Components/Gallary/Gallary.js
  src/Pages/Detail/Components/Gallary/Gallary.scss
  src/Pages/Detail/Components/Modals/AlertModal/AlertModal.js
  src/Pages/Detail/Components/Modals/AlertModal/AlertModal.scss
  src/Pages/Detail/Components/Modals/CommentModal/CommentModal.js
  src/Pages/Detail/Components/Modals/CommentModal/CommentModal.scss
  src/Pages/Detail/Components/Modals/ReviewModal/ReviewModal.js
  src/Pages/Detail/Components/Modals/ReviewModal/ReviewModal.scss
  src/Pages/Detail/Components/Modals/ReviewModal/statusButtons/WatchingButton/WatchingButton.js
  src/Pages/Detail/Components/Modals/ReviewModal/statusButtons/WatchingButton/WatchingButton.scss
  src/Pages/Detail/Components/Modals/ReviewModal/statusButtons/WishButton/WishButton.js
  src/Pages/Detail/Components/Modals/ReviewModal/statusButtons/WishButton/WishButton.scss
  src/Pages/Detail/Detail.js
  src/Pages/Detail/Detail.scss
Labels: Status: 리뷰 요청

#11 [박주엽]ADD: 공용 Footer 레이아웃 작성
  src/Components/Footer/Components/InfoContainer/InfoContainer.js
  src/Components/Footer/Components/InfoContainer/InfoContainer.scss
  src/Components/Footer/Components/InfoContainerRight/InfoContainerRight.js
  src/Components/Footer/Components/InfoContainerRight/InfoContainerRight.scss
  src/Components/Footer/Components/RatingSummary/RatingSummary.js
  src/Components/Footer/Components/RatingSummary/RatingSummary.scss
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
Labels: Status: 도움 요청, Status: 수정 요청

#12 [류상욱] Add: 네비게이션바 레이아웃, 기능 구현 완료
  .gitignore
  public/images/modal/check_icon.svg
  public/images/modal/delete_icon.svg
  public/images/modal/facebook_icon.svg
  public/images/modal/warning_icon.svg
  public/images/modal/watcha_logo.svg
  public/images/nav/search_icon.svg
  src/Components/FoolIcon/FoolIcon.js
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Pages/Main/Main.js
  src/Pages/Modal/Login.js
  src/Pages/Modal/Login.scss
  src/Pages/Modal/SignUp.js
  src/Pages/Modal/SignUp.scss
  src/Pages/UserProfile/UserProfile.scss
  src/config.js
Labels: Status: 리뷰 요청

#13 [김동호] ADD: Detail페이지 하단 컨테이너 부분 작성
  public/data/DetailPageMockData/mockDetail.json
  src/Pages/Detail/Components/CommentContainer/CommentContainer.js
  src/Pages/Detail/Components/CommentContainer/CommentContainer.scss
  src/Pages/Detail/Components/ContentsContainer/ContentsContainer.js
  src/Pages/Detail/Components/ContentsContainer/ContentsContainer.scss
  src/Pages/Detail/Components/DetailContainer/Collection/Collection.js
  src/Pages/Detail/Components/DetailContainer/Collection/Collection.scss
  src/Pages/Detail/Components/DetailContainer/CommentContainer/CommentContainer.js
  src/Pages/Detail/Components/DetailContainer/CommentContainer/CommentContainer.scss
  src/Pages/Detail/Components/DetailContainer/ContentSlider/ContentSlider.js
  src/Pages/Detail/Components/DetailContainer/ContentSlider/ContentSlider.scss
  src/Pages/Detail/Components/DetailContainer/ContentSlider/SliderButton/SliderButton.js
  src/Pages/Detail/Components/DetailContainer/ContentSlider/SliderButton/SliderButton.scss
  src/Pages/Detail/Components/DetailContainer/ContentsAside/ContentsAside.js
  src/Pages/Detail/Components/DetailContainer/ContentsAside/ContentsAside.scss
  src/Pages/Detail/Components/DetailContainer/ContentsAside/Gallary/Gallary.js
  src/Pages/Detail/Components/DetailContainer/ContentsAside/Gallary/Gallary.scss
  src/Pages/Detail/Components/DetailContainer/ContentsAside/MediaItems/MediaButtons/MediaButtons.js
  src/Pages/Detail/Components/DetailContainer/ContentsAside/MediaItems/MediaButtons/MediaButtons.scss
  src/Pages/Detail/Components/DetailContainer/ContentsAside/MediaItems/MediaItems.js
  src/Pages/Detail/Components/DetailContainer/ContentsAside/MediaItems/MediaItems.scss
  src/Pages/Detail/Components/DetailContainer/ContentsAside/Videos/Videos.js
  src/Pages/Detail/Components/DetailContainer/ContentsAside/Videos/Videos.scss
  src/Pages/Detail/Components/DetailContainer/DescriptionContainer/DescriptionContainer.js
  src/Pages/Detail/Components/DetailContainer/DescriptionContainer/DescriptionContainer.scss
  src/Pages/Detail/Components/DetailContainer/DetailContainer.js
  src/Pages/Detail/Components/DetailContainer/DetailContainer.scss
  src/Pages/Detail/Components/DetailContainer/Gallary/Gallary.js
  src/Pages/Detail/Components/DetailContainer/Gallary/Gallary.scss
  src/Pages/Detail/Components/DetailContainer/PersonInvolved/PersonInvolved.js
  src/Pages/Detail/Components/DetailContainer/PersonInvolved/PersonInvolved.scss
  src/Pages/Detail/Components/DetailContainer/RatingGraph/RatingGraph.js
  src/Pages/Detail/Components/DetailContainer/RatingGraph/RatingGraph.scss
  src/Pages/Detail/Components/DetailContainer/ThumbnailImage/ThumbnailImage.js
  src/Pages/Detail/Components/DetailHeader/DetailHeader.js
  src/Pages/Detail/Components/DetailHeader/HeaderPanelContainer/ButtonBlocks/StatusButtonBlock/StatusButtonBlock.js
  src/Pages/Detail/Components/DetailHeader/HeaderPanelContainer/HeaderPanelContainer.js
  src/Pages/Detail/Components/DetailHeader/HeaderPanelContainer/SelfRating/SelfRating.js
  src/Pages/Detail/Components/DetailHeader/HeaderPosterContainer/HeaderPosterContainer.js
  src/Pages/Detail/Components/Modals/AlertModal/AlertModal.js
  src/Pages/Detail/Detail.js
  src/Pages/Detail/Detail.scss
Labels: Status: 리뷰 요청

#15 [박주엽]ADD: CollectionPage 레이아웃 및 기능
  public/data/MainPageMockData/CollectionPageMoctData.json
  src/Pages/Collection/Components/CollectionHeader/CollectionHeader.js
  src/Pages/Collection/Components/CollectionHeader/CollectionHeader.scss
  src/Pages/Collection/Components/CollectionPage/CollectionPage.js
  src/Pages/Collection/Components/CollectionPosterItem/CollectionPosterItem.js
  src/Pages/Collection/Components/CollectionPosterItem/CollectionPosterItem.scss
  src/Pages/Collection/Components/CollectionPosters/CollectionPosters.js
  src/Pages/Collection/Components/CollectionPosters/CollectionPosters.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#16 [김동호] ADD: 데이터 통신 부분 작성
  package-lock.json
  package.json
  src/Pages/Detail/Components/DetailContainer/ContentsAside/MediaItems/MediaButtons/MediaButtons.js
  src/Pages/Detail/Components/DetailContainer/RatingGraph/RatingGraph.js
  src/Pages/Detail/Components/DetailContainer/SelfCommentBlock/SelfCommentBlock.js
  src/Pages/Detail/Components/DetailHeader/DetailHeader.js
  src/Pages/Detail/Components/DetailHeader/HeaderPanelContainer/ButtonBlocks/NomalButtonBlock/NomalButtonBlock.js
  src/Pages/Detail/Components/DetailHeader/HeaderPanelContainer/ButtonBlocks/StatusButtonBlock/StatusButtonBlock.js
  src/Pages/Detail/Components/DetailHeader/HeaderPanelContainer/HeaderPanelContainer.js
  src/Pages/Detail/Components/DetailHeader/HeaderPanelContainer/SelfRating/SelfRating.js
  src/Pages/Detail/Components/DetailHeader/HeaderPosterContainer/HeaderPosterContainer.js
  src/Pages/Detail/Components/Modals/RejectModal/RejectModal.js
  src/Pages/Detail/Components/Modals/RejectModal/RejectModal.scss
  src/Pages/Detail/Components/Modals/ReviewModal/ReviewModal.js
  src/Pages/Detail/Detail.js
  src/Pages/Detail/Detail.scss
  src/Pages/Detail/api.js
Labels: Status: 리뷰 요청

#17 [박주엽] Add: MainPage 컴포넌트 추가
  src/Pages/Main/Components/MainContainer/MainContainer.js
Labels: Status: 리뷰 요청

#20 [박주엽]ADD: Routes 적용 및 Nav 변경
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Pages/Main/Components/Collection/CollectionItem/CollectionItem.js
  src/Pages/Main/Components/Collection/CollectionPosters/CollectionPosters.js
  src/Pages/Main/Components/MoviePosterItem/MoviePosterItem.js
  src/Pages/Main/Components/MoviePosterItem/MoviePosterItem.scss
  src/Pages/Main/Components/MoviePosters/MoviePosters.js
  src/Pages/UserProfile/UserProfile.js
Labels: Status: 리뷰 요청
